spring:
  data:
    mongodb:
      database: SpringMongoCrud
      uri: mongodb+srv://root:root@springmongocrud.bk7o9.mongodb.net/?retryWrites=true&w=majority&appName=SpringMongoCrud
      username: root
      password: root