server:
  port: 8081

spring:
  application:
    name: crud-operation-using-mongodb
  profiles:
    active: mongodb

management:
  endpoints:
    web:
      exposure:
#        include: health,info  # Include specific endpoints
         include: '*'  # Include all endpoints
        # exclude: beans,env  # Exclude specific endpoints
      base-path: /manage
      request:
        request-logging:
          enabled: true
  cors:
    allowed-origins: http://localhost:8081
    allowed-methods: GET,POST
