server:
  port: 8081

spring:
  application:
    name: mongodb-redis-cache
  redis:
    host: localhost
    port: 6379
  data:
    mongodb:
      uri:
      username: root
      password: root
      database: SpringMongoCrud
  cache:
    type: redis